### ISSUE TITLE
patch: reproductible build

### ISSUE THREAD

**Issue by bastien-roucaries** [andrewrk/browserify-lite#12]
Hi could you apply the following patch, that ease reproductible build:
```
Index: node-browserify-lite/index.js
===================================================================
--- node-browserify-lite.orig/index.js
+++ node-browserify-lite/index.js
@@ -79,6 +79,8 @@ function renderBundle(options, cb) {
 
   function render(entrySourcePath, cb) {
     var modules = Object.keys(sources);
+    // for reproductible build
+    module.sort();
     var aliases = {};
     modules.forEach(function(canonicalSourcePath, index) {
       aliases[canonicalSourcePath] = index;
```

**Comment by andrewrk** [comment]
sure, can you make a pull request?

**Comment by rebecca-palmer** [comment]
The above patch turned out not to fix all the reproducibility issues ([test results](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/theano.html), scroll down to /usr/share/doc/theano-doc/html/_static/d3viz/js/graphlib-dot.min.js).

#13 extends it into something that should, but has not yet had much testing.

[Debian discussion](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=941309) of this fix.  [General background](https://reproducible-builds.org/) on why reproducibility matters.
