### ISSUE TITLE
please help me get JsSIP.js working with browserify-lite

### ISSUE THREAD

**Issue by dpocock** [andrewrk/browserify-lite#6]
It doesn't appear to be correctly resolving all require statements after the braces change.

I just generated a new JsSIP.js - you can see it at https://fedrtc.org/test/

Notice it fails:

```
Uncaught TypeError: util.inherits is not a function    (line 17525)
Uncaught ReferenceError: JsSIP is not defined
```

**Comment by andrewrk** [comment]
I looked at the code. The line that has the problem is calling `util.inherits`.

The `util` module defines inherits like this:

`exports.inherits = require('inherits');`

The `inherits` module defines `module.exports` like this:

`module.exports = require('util').inherits`

This is a circular dependency.

**Comment by dpocock** [comment]
Thanks for spotting that.

It turns out my system had somehow reverted to node-inherits 2.0.1-1 during a dist-upgrade.  I fixed that and also added a more explicit dependency in the node-inherits package to help other people avoid problems:

http://anonscm.debian.org/cgit/pkg-javascript/node-inherits.git/commit/?id=64af841ec03fa2bc0c1d9d7de132f12fa802edb9

With libjs-inherits and node-inherits 2.0.1-3 now on my system it seems to work fine.

Should browserify-lite detect and/or warn about cyclic dependencies like that?  Maybe that would require a more sophisticated parser though.

Now that I've made a successful build of JsSIP with your latest browserify-lite from master, could you please tag it and upload it to Debian?  Then I will be able to upload the JsSIP package.

**Comment by andrewrk** [comment]
> Should browserify-lite detect and/or warn about cyclic dependencies like that? Maybe that would require a more sophisticated parser though.

I agree that would be nice, but browserify-lite isn't meant to be an advanced packaging tool, it's just a bare minimum replacement to get the job done.

> Now that I've made a successful build of JsSIP with your latest browserify-lite from master, could you please tag it and upload it to Debian? Then I will be able to upload the JsSIP package.

Nice, glad that you got it working. I'll work on getting it uploaded. I don't have DM privileges so if you're a DD you could sponsor the upload. Otherwise we'll both wait on one of my sponsors to find time to do the upload.

**Comment by dpocock** [comment]
I'll be happy to sponsor the upload, can you just email me and CC the previous sponsors and let me know the procedure they have used?  E.g. do you upload it to mentors.debian.net or does the sponsor just grab it from your tag in Github?

**Comment by andrewrk** [comment]
Yep, let's handle it via email from here.
